version: "3"

services:
    web_service:
      container_name: nodeContainer
      restart: always
      build: .
      ports:
        - "8080:4000"
      links:
        - dbp2
      volumes:
        - .:/usr/src/app/src
    dbp2:
      container_name: mongoDatabase
      image: mongo
      ports:
        - "27020:27017"
      logging:
        driver: none
